# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '2.10界面.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QApplication, QMainWindow


class Ui_Form(QMainWindow):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(561, 534)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 10, 541, 511))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        self.textEdit.setStyleSheet("background-color: white;\n"
"    color: black;\n"
"    border: 2px solid #4080ff;\n"
"    border-radius: 10px;\n"
"    padding: 10px 20px;\n"
"    font-family: Arial;\n"
"    font-size: 16px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    qproperty-icon: url(:/images/icon.png);")
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.textEdit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setStyleSheet("background-color: white;\n"
"    color: black;\n"
"    border: 2px solid #4080ff;\n"
"    border-radius: 10px;\n"
"    padding: 10px 20px;\n"
"    font-family: Arial;\n"
"    font-size: 12px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    qproperty-icon: url(:/images/icon.png);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setStyleSheet("background-color: white;\n"
"    color: black;\n"
"    border: 2px solid #4080ff;\n"
"    border-radius: 10px;\n"
"    padding: 10px 20px;\n"
"    font-family: Arial;\n"
"    font-size: 16px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    qproperty-icon: url(:/images/icon.png);")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setStyleSheet("background-color: white;\n"
                                            "    color: black;\n"
                                        "    border: 2px solid #4080ff;\n"
                                        "    border-radius: 10px;\n"
                                        "    padding: 10px 20px;\n"
                                        "    font-family: Arial;\n"
                                        "    font-size: 12px;\n"
                                        "    text-align: center;\n"
                                        "    text-decoration: none;\n"
                                        "    qproperty-icon: url(:/images/icon.png);")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_2.setText(_translate("Form", "上传文件"))
        self.lineEdit.setPlaceholderText(_translate("Form", "请输入内容...."))
        self.pushButton.setText(_translate("Form", "发送"))


if __name__ == '__main__':
    app = QApplication(sys.argv)
    mainwindow = QMainWindow()
    ui = Ui_Form()
    ui.setupUi(mainwindow)
    mainwindow.show()
    app.exec()
