# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '2.10界面.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QWidget, QApplication


class Ui_Form(QWidget):
    def __init__(self):
        super(Ui_Form, self).__init__()
        self.setupUi(self)

    def setupUi(self, form):
        form.resize(561, 534)
        self.widget = QtWidgets.QWidget(form)  # 创建对象
        # 设置大小，绘制矩形区域
        self.widget.setGeometry(QtCore.QRect(10, 10, 541, 511))
        # 设置外部容器
        self.container = QtWidgets.QVBoxLayout(self.widget)

        # 调整内容区域与窗口边框之间的间距。
        self.container.setContentsMargins(0, 0, 0, 0)

        # 聊天记录显示
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        # 设置样式
        self.textEdit.setStyleSheet("background-color: white;\n"
                                    "    color: black;\n"
                                    "    border: 2px solid #4080ff;\n"
                                    "    border-radius: 10px;\n"
                                    "    padding: 10px 20px;\n"
                                    "    font-family: Arial;\n"
                                    "    font-size: 16px;\n"
                                    "    text-align: center;\n"
                                    "    text-decoration: none;\n"
                                    "    qproperty-icon: url(:/images/icon.png);")
        # 设置聊天记录只读读性
        self.textEdit.setReadOnly(True)

        # 添加聊天记录框到外层容器
        self.container.addWidget(self.textEdit)

        # 设置水平容器容纳两个按钮和输入框
        self.horizontalLayout = QtWidgets.QHBoxLayout()

        self.btn_load = QtWidgets.QPushButton(self.widget)
        self.btn_load.setStyleSheet("background-color: white;\n"
                                    "    color: black;\n"
                                    "    border: 2px solid #4080ff;\n"
                                    "    border-radius: 10px;\n"
                                    "    padding: 10px 20px;\n"
                                    "    font-family: Arial;\n"
                                    "    font-size: 12px;\n"
                                    "    text-align: center;\n"
                                    "    text-decoration: none;\n"
                                    "    qproperty-icon: url(:/images/icon.png);")

        self.horizontalLayout.addWidget(self.btn_load)

        # 创建输入框
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setStyleSheet("background-color: white;\n"
                                    "    color: black;\n"
                                    "    border: 2px solid #4080ff;\n"
                                    "    border-radius: 10px;\n"
                                    "    padding: 10px 20px;\n"
                                    "    font-family: Arial;\n"
                                    "    font-size: 16px;\n"
                                    "    text-align: center;\n"
                                    "    text-decoration: none;\n"
                                    "    qproperty-icon: url(:/images/icon.png);")

        self.horizontalLayout.addWidget(self.lineEdit)
        self.btn_send = QtWidgets.QPushButton()
        self.btn_send.setStyleSheet("background-color: white;\n"
                                      "    color: black;\n"
                                      "    border: 2px solid #4080ff;\n"
                                      "    border-radius: 10px;\n"
                                      "    padding: 10px 20px;\n"
                                      "    font-family: Arial;\n"
                                      "    font-size: 12px;\n"
                                      "    text-align: center;\n"
                                      "    text-decoration: none;\n"
                                      "    qproperty-icon: url(:/images/icon.png);")
        self.btn_send.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.btn_send)
        self.container.addLayout(self.horizontalLayout)

        self.retranslateUi(form)
        QtCore.QMetaObject.connectSlotsByName(form)

    def retranslateUi(self, form):
        _translate = QtCore.QCoreApplication.translate
        form.setWindowTitle('界面')
        self.btn_load.setText(_translate("Form", "上传文件"))
        self.lineEdit.setPlaceholderText(_translate("Form", "请输入内容...."))
        self.btn_send.setText(_translate("Form", "发送"))


if __name__ == '__main__':
    app = QApplication(sys.argv)
    w = Ui_Form()
    w.show()
    app.exec()
